
"use client";

import { useForm, useFieldArray } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { useApp } from '@/hooks/use-app';
import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from "@/hooks/use-toast";
import { Textarea } from '@/components/ui/textarea';
import { useState } from 'react';
import { PlusCircle, Trash2 } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Separator } from '@/components/ui/separator';

const formSchema = z.object({
  title: z.string().min(10, {
    message: "Title must be at least 10 characters.",
  }).max(100, {
    message: "Title must not exceed 100 characters.",
  }),
  options: z.array(z.object({
    text: z.string().min(2, "Option text must be at least 2 characters.").max(50, "Option text must not exceed 50 characters."),
    odds: z.string().refine((val) => !isNaN(parseFloat(val)) && parseFloat(val) >= 1, {
        message: "Odds must be a number equal to or greater than 1.",
    }),
  })).min(2, "You must provide at least two options."),
});

export default function AdminPage() {
  const { scenarios, addScenario, resolveScenario } = useApp();
  const { toast } = useToast();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [selections, setSelections] = useState<Record<string, string>>({});

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      title: "",
      options: [{ text: "", odds: "" }, { text: "", odds: "" }],
    },
  });

  const { fields, append, remove } = useFieldArray({
    control: form.control,
    name: "options"
  });

  async function onSubmit(values: z.infer<typeof formSchema>) {
    setIsSubmitting(true);
    await addScenario(values);
    toast({
      title: "It is Written!",
      description: "A new scenario has been created and is open for joyful wagers.",
    });
    form.reset({
      title: "",
      options: [{ text: "", odds: "" }, { text: "", odds: "" }],
    });
    setIsSubmitting(false);
  }

  const handleResolve = (scenarioId: string) => {
    const winningIndexStr = selections[scenarioId];
    if (winningIndexStr === undefined) {
        toast({ variant: "destructive", title: "No selection", description: "Please select a winning option." });
        return;
    }
    const winningIndex = parseInt(winningIndexStr, 10);
    resolveScenario(scenarioId, winningIndex);
    toast({ title: "Scenario Resolved!", description: "The outcome has been decided and winners (if any) have been paid." });
  };

  const openScenarios = scenarios.filter(s => s.status === 'open');

  return (
    <div className="space-y-8 max-w-4xl mx-auto">
      <Card>
        <CardHeader>
          <CardTitle className="font-headline text-2xl">Add New Scenario</CardTitle>
          <CardDescription>
            Create a new fun scenario with multiple options and odds. An amusing description will be generated by AI.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              <FormField
                control={form.control}
                name="title"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Scenario Title</FormLabel>
                    <FormControl>
                      <Textarea placeholder="e.g., Will the choir's new robe colors be a heavenly hit?" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <div>
                <FormLabel>Options</FormLabel>
                <FormDescription className="mb-2">Add at least two options with their respective odds.</FormDescription>
                <div className="space-y-4">
                  {fields.map((field, index) => (
                    <div key={field.id} className="flex items-start gap-2">
                      <FormField
                        control={form.control}
                        name={`options.${index}.text`}
                        render={({ field }) => (
                          <FormItem className="flex-1">
                            <FormControl>
                              <Input placeholder={`Option ${index + 1} Text`} {...field} />
                            </FormControl>
                             <FormMessage />
                          </FormItem>
                        )}
                      />
                       <FormField
                        control={form.control}
                        name={`options.${index}.odds`}
                        render={({ field }) => (
                          <FormItem className="w-24">
                            <FormControl>
                              <Input type="number" placeholder="Odds" {...field} step="0.1" />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                      <Button type="button" variant="ghost" size="icon" onClick={() => remove(index)} disabled={fields.length <= 2}>
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </div>
                  ))}
                </div>
                 <FormMessage>{form.formState.errors.options?.message}</FormMessage>
              </div>

              <div className="flex justify-between items-center">
                <Button type="button" variant="outline" onClick={() => append({ text: "", odds: "" })}>
                  <PlusCircle className="mr-2 h-4 w-4" />
                  Add Option
                </Button>
                <Button type="submit" disabled={isSubmitting}>
                  {isSubmitting ? 'Adding...' : 'Add Scenario with AI'}
                </Button>
              </div>
            </form>
          </Form>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="font-headline text-2xl">Resolve Open Scenarios</CardTitle>
          <CardDescription>Select the winning option to close betting and pay out winners.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {openScenarios.length > 0 ? openScenarios.map((scenario, index) => (
            <div key={scenario.id}>
              <div className="flex justify-between items-center gap-4 p-4 border rounded-lg">
                <p className="font-medium flex-1">{scenario.title}</p>
                <div className="flex items-center gap-2">
                  <Select onValueChange={(value) => setSelections(prev => ({ ...prev, [scenario.id]: value }))}>
                    <SelectTrigger className="w-[250px]">
                      <SelectValue placeholder="Select winning option" />
                    </SelectTrigger>
                    <SelectContent>
                      {scenario.options.map((option, idx) => (
                        <SelectItem key={idx} value={String(idx)}>
                          {option.text}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <Button onClick={() => handleResolve(scenario.id)} disabled={!selections[scenario.id]}>
                    Resolve
                  </Button>
                </div>
              </div>
              {index < openScenarios.length - 1 && <Separator className="my-6"/>}
            </div>
          )) : (
            <p className="text-muted-foreground text-center">No scenarios are currently open for resolution.</p>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
